spring:
  application:
    name: MetricsConsumer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/kafkaData
    username: root
    password: 123
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: java.util
        isolation.level: read_committed
      listener:
        type: batch
server:
  port: 8280
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG